from __future__ import annotations
import numpy as np
import typing
from typing import Protocol
from typing import TypeVar
from typing import TypedDict
from typing import runtime_checkable
__all__ = ['DTypeLike', 'Protocol', 'TypeVar', 'TypedDict', 'np', 'runtime_checkable']
class _DTypeDict(dict):
    __optional_keys__: typing.ClassVar[frozenset]  # value = frozenset({'offsets', 'titles', 'itemsize', 'aligned'})
    __required_keys__: typing.ClassVar[frozenset]  # value = frozenset({'names', 'formats'})
    __total__: typing.ClassVar[bool] = False
class _DTypeDictBase(dict):
    __optional_keys__: typing.ClassVar[frozenset]  # value = frozenset()
    __orig_bases__: typing.ClassVar[tuple] = (typing.TypedDict)
    __required_keys__: typing.ClassVar[frozenset]  # value = frozenset({'names', 'formats'})
    __total__: typing.ClassVar[bool] = True
class _SupportsDType(typing.Protocol):
    __abstractmethods__: typing.ClassVar[frozenset]  # value = frozenset()
    __orig_bases__: typing.ClassVar[tuple]  # value = (typing.Protocol[+_DType_co])
    __parameters__: typing.ClassVar[tuple]  # value = (+_DType_co)
    _abc_impl: typing.ClassVar[_abc._abc_data]  # value = <_abc._abc_data object>
    _is_protocol: typing.ClassVar[bool] = True
    _is_runtime_protocol: typing.ClassVar[bool] = True
    @staticmethod
    def __subclasshook__(other):
        ...
    def __init__(self, *args, **kwargs):
        ...
    @property
    def dtype(self) -> +_DType_co:
        ...
DTypeLike: typing._UnionGenericAlias  # value = typing.Union[numpy.dtype[typing.Any], NoneType, type[typing.Any], numpy._typing._dtype_like._SupportsDType[numpy.dtype[typing.Any]], str, tuple[typing.Any, int], tuple[typing.Any, typing.Union[typing.SupportsIndex, collections.abc.Sequence[typing.SupportsIndex]]], list[typing.Any], numpy._typing._dtype_like._DTypeDict, tuple[typing.Any, typing.Any]]
_BoolCodes: typing._LiteralGenericAlias  # value = typing.Literal['?', '=?', '<?', '>?', 'bool', 'bool_', 'bool8']
_ByteCodes: typing._LiteralGenericAlias  # value = typing.Literal['byte', 'b', '=b', '<b', '>b']
_BytesCodes: typing._LiteralGenericAlias  # value = typing.Literal['bytes', 'bytes_', 'bytes0', 'S', '=S', '<S', '>S']
_CDoubleCodes: typing._LiteralGenericAlias  # value = typing.Literal['cdouble', 'complex', 'complex_', 'cfloat', 'D', '=D', '<D', '>D']
_CLongDoubleCodes: typing._LiteralGenericAlias  # value = typing.Literal['clongdouble', 'clongfloat', 'longcomplex', 'G', '=G', '<G', '>G']
_CSingleCodes: typing._LiteralGenericAlias  # value = typing.Literal['csingle', 'singlecomplex', 'F', '=F', '<F', '>F']
_Complex128Codes: typing._LiteralGenericAlias  # value = typing.Literal['complex128', 'c16', '=c16', '<c16', '>c16']
_Complex64Codes: typing._LiteralGenericAlias  # value = typing.Literal['complex64', 'c8', '=c8', '<c8', '>c8']
_DT64Codes: typing._LiteralGenericAlias  # value = typing.Literal['datetime64', '=datetime64', '<datetime64', '>datetime64', 'datetime64[Y]', '=datetime64[Y]', '<datetime64[Y]', '>datetime64[Y]', 'datetime64[M]', '=datetime64[M]', '<datetime64[M]', '>datetime64[M]', 'datetime64[W]', '=datetime64[W]', '<datetime64[W]', '>datetime64[W]', 'datetime64[D]', '=datetime64[D]', '<datetime64[D]', '>datetime64[D]', 'datetime64[h]', '=datetime64[h]', '<datetime64[h]', '>datetime64[h]', 'datetime64[m]', '=datetime64[m]', '<datetime64[m]', '>datetime64[m]', 'datetime64[s]', '=datetime64[s]', '<datetime64[s]', '>datetime64[s]', 'datetime64[ms]', '=datetime64[ms]', '<datetime64[ms]', '>datetime64[ms]', 'datetime64[us]', '=datetime64[us]', '<datetime64[us]', '>datetime64[us]', 'datetime64[ns]', '=datetime64[ns]', '<datetime64[ns]', '>datetime64[ns]', 'datetime64[ps]', '=datetime64[ps]', '<datetime64[ps]', '>datetime64[ps]', 'datetime64[fs]', '=datetime64[fs]', '<datetime64[fs]', '>datetime64[fs]', 'datetime64[as]', '=datetime64[as]', '<datetime64[as]', '>datetime64[as]', 'M', '=M', '<M', '>M', 'M8', '=M8', '<M8', '>M8', 'M8[Y]', '=M8[Y]', '<M8[Y]', '>M8[Y]', 'M8[M]', '=M8[M]', '<M8[M]', '>M8[M]', 'M8[W]', '=M8[W]', '<M8[W]', '>M8[W]', 'M8[D]', '=M8[D]', '<M8[D]', '>M8[D]', 'M8[h]', '=M8[h]', '<M8[h]', '>M8[h]', 'M8[m]', '=M8[m]', '<M8[m]', '>M8[m]', 'M8[s]', '=M8[s]', '<M8[s]', '>M8[s]', 'M8[ms]', '=M8[ms]', '<M8[ms]', '>M8[ms]', 'M8[us]', '=M8[us]', '<M8[us]', '>M8[us]', 'M8[ns]', '=M8[ns]', '<M8[ns]', '>M8[ns]', 'M8[ps]', '=M8[ps]', '<M8[ps]', '>M8[ps]', 'M8[fs]', '=M8[fs]', '<M8[fs]', '>M8[fs]', 'M8[as]', '=M8[as]', '<M8[as]', '>M8[as]']
_DTypeLike: typing._UnionGenericAlias  # value = typing.Union[numpy.dtype[~_SCT], type[~_SCT], numpy._typing._dtype_like._SupportsDType[numpy.dtype[~_SCT]]]
_DTypeLikeBool: typing._UnionGenericAlias  # value = typing.Union[type[bool], type[numpy.bool_], numpy.dtype[numpy.bool_], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.bool_]], typing.Literal['?', '=?', '<?', '>?', 'bool', 'bool_', 'bool8']]
_DTypeLikeBytes: typing._UnionGenericAlias  # value = typing.Union[type[bytes], type[numpy.bytes_], numpy.dtype[numpy.bytes_], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.bytes_]], typing.Literal['bytes', 'bytes_', 'bytes0', 'S', '=S', '<S', '>S']]
_DTypeLikeComplex: typing._UnionGenericAlias  # value = typing.Union[type[complex], type[numpy.complexfloating], numpy.dtype[numpy.complexfloating], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.complexfloating]], typing.Literal['complex64', 'c8', '=c8', '<c8', '>c8'], typing.Literal['complex128', 'c16', '=c16', '<c16', '>c16'], typing.Literal['csingle', 'singlecomplex', 'F', '=F', '<F', '>F'], typing.Literal['cdouble', 'complex', 'complex_', 'cfloat', 'D', '=D', '<D', '>D'], typing.Literal['clongdouble', 'clongfloat', 'longcomplex', 'G', '=G', '<G', '>G']]
_DTypeLikeComplex_co: typing._UnionGenericAlias  # value = typing.Union[type[bool], type[numpy.bool_], numpy.dtype[numpy.bool_], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.bool_]], typing.Literal['?', '=?', '<?', '>?', 'bool', 'bool_', 'bool8'], type[numpy.unsignedinteger], numpy.dtype[numpy.unsignedinteger], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.unsignedinteger]], typing.Literal['uint8', 'u1', '=u1', '<u1', '>u1'], typing.Literal['uint16', 'u2', '=u2', '<u2', '>u2'], typing.Literal['uint32', 'u4', '=u4', '<u4', '>u4'], typing.Literal['uint64', 'u8', '=u8', '<u8', '>u8'], typing.Literal['ubyte', 'B', '=B', '<B', '>B'], typing.Literal['ushort', 'H', '=H', '<H', '>H'], typing.Literal['uintc', 'I', '=I', '<I', '>I'], typing.Literal['uintp', 'uint0', 'P', '=P', '<P', '>P'], typing.Literal['ulong', 'uint', 'L', '=L', '<L', '>L'], typing.Literal['ulonglong', 'Q', '=Q', '<Q', '>Q'], type[int], type[numpy.signedinteger], numpy.dtype[numpy.signedinteger], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.signedinteger]], typing.Literal['int8', 'i1', '=i1', '<i1', '>i1'], typing.Literal['int16', 'i2', '=i2', '<i2', '>i2'], typing.Literal['int32', 'i4', '=i4', '<i4', '>i4'], typing.Literal['int64', 'i8', '=i8', '<i8', '>i8'], typing.Literal['byte', 'b', '=b', '<b', '>b'], typing.Literal['short', 'h', '=h', '<h', '>h'], typing.Literal['intc', 'i', '=i', '<i', '>i'], typing.Literal['intp', 'int0', 'p', '=p', '<p', '>p'], typing.Literal['long', 'int', 'int_', 'l', '=l', '<l', '>l'], typing.Literal['longlong', 'q', '=q', '<q', '>q'], type[float], type[numpy.floating], numpy.dtype[numpy.floating], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.floating]], typing.Literal['float16', 'f2', '=f2', '<f2', '>f2'], typing.Literal['float32', 'f4', '=f4', '<f4', '>f4'], typing.Literal['float64', 'f8', '=f8', '<f8', '>f8'], typing.Literal['half', 'e', '=e', '<e', '>e'], typing.Literal['single', 'f', '=f', '<f', '>f'], typing.Literal['double', 'float', 'float_', 'd', '=d', '<d', '>d'], typing.Literal['longdouble', 'longfloat', 'g', '=g', '<g', '>g'], type[complex], type[numpy.complexfloating], numpy.dtype[numpy.complexfloating], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.complexfloating]], typing.Literal['complex64', 'c8', '=c8', '<c8', '>c8'], typing.Literal['complex128', 'c16', '=c16', '<c16', '>c16'], typing.Literal['csingle', 'singlecomplex', 'F', '=F', '<F', '>F'], typing.Literal['cdouble', 'complex', 'complex_', 'cfloat', 'D', '=D', '<D', '>D'], typing.Literal['clongdouble', 'clongfloat', 'longcomplex', 'G', '=G', '<G', '>G']]
_DTypeLikeDT64: typing._UnionGenericAlias  # value = typing.Union[type[numpy.timedelta64], numpy.dtype[numpy.timedelta64], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.timedelta64]], typing.Literal['timedelta64', '=timedelta64', '<timedelta64', '>timedelta64', 'timedelta64[Y]', '=timedelta64[Y]', '<timedelta64[Y]', '>timedelta64[Y]', 'timedelta64[M]', '=timedelta64[M]', '<timedelta64[M]', '>timedelta64[M]', 'timedelta64[W]', '=timedelta64[W]', '<timedelta64[W]', '>timedelta64[W]', 'timedelta64[D]', '=timedelta64[D]', '<timedelta64[D]', '>timedelta64[D]', 'timedelta64[h]', '=timedelta64[h]', '<timedelta64[h]', '>timedelta64[h]', 'timedelta64[m]', '=timedelta64[m]', '<timedelta64[m]', '>timedelta64[m]', 'timedelta64[s]', '=timedelta64[s]', '<timedelta64[s]', '>timedelta64[s]', 'timedelta64[ms]', '=timedelta64[ms]', '<timedelta64[ms]', '>timedelta64[ms]', 'timedelta64[us]', '=timedelta64[us]', '<timedelta64[us]', '>timedelta64[us]', 'timedelta64[ns]', '=timedelta64[ns]', '<timedelta64[ns]', '>timedelta64[ns]', 'timedelta64[ps]', '=timedelta64[ps]', '<timedelta64[ps]', '>timedelta64[ps]', 'timedelta64[fs]', '=timedelta64[fs]', '<timedelta64[fs]', '>timedelta64[fs]', 'timedelta64[as]', '=timedelta64[as]', '<timedelta64[as]', '>timedelta64[as]', 'm', '=m', '<m', '>m', 'm8', '=m8', '<m8', '>m8', 'm8[Y]', '=m8[Y]', '<m8[Y]', '>m8[Y]', 'm8[M]', '=m8[M]', '<m8[M]', '>m8[M]', 'm8[W]', '=m8[W]', '<m8[W]', '>m8[W]', 'm8[D]', '=m8[D]', '<m8[D]', '>m8[D]', 'm8[h]', '=m8[h]', '<m8[h]', '>m8[h]', 'm8[m]', '=m8[m]', '<m8[m]', '>m8[m]', 'm8[s]', '=m8[s]', '<m8[s]', '>m8[s]', 'm8[ms]', '=m8[ms]', '<m8[ms]', '>m8[ms]', 'm8[us]', '=m8[us]', '<m8[us]', '>m8[us]', 'm8[ns]', '=m8[ns]', '<m8[ns]', '>m8[ns]', 'm8[ps]', '=m8[ps]', '<m8[ps]', '>m8[ps]', 'm8[fs]', '=m8[fs]', '<m8[fs]', '>m8[fs]', 'm8[as]', '=m8[as]', '<m8[as]', '>m8[as]']]
_DTypeLikeFloat: typing._UnionGenericAlias  # value = typing.Union[type[float], type[numpy.floating], numpy.dtype[numpy.floating], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.floating]], typing.Literal['float16', 'f2', '=f2', '<f2', '>f2'], typing.Literal['float32', 'f4', '=f4', '<f4', '>f4'], typing.Literal['float64', 'f8', '=f8', '<f8', '>f8'], typing.Literal['half', 'e', '=e', '<e', '>e'], typing.Literal['single', 'f', '=f', '<f', '>f'], typing.Literal['double', 'float', 'float_', 'd', '=d', '<d', '>d'], typing.Literal['longdouble', 'longfloat', 'g', '=g', '<g', '>g']]
_DTypeLikeInt: typing._UnionGenericAlias  # value = typing.Union[type[int], type[numpy.signedinteger], numpy.dtype[numpy.signedinteger], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.signedinteger]], typing.Literal['int8', 'i1', '=i1', '<i1', '>i1'], typing.Literal['int16', 'i2', '=i2', '<i2', '>i2'], typing.Literal['int32', 'i4', '=i4', '<i4', '>i4'], typing.Literal['int64', 'i8', '=i8', '<i8', '>i8'], typing.Literal['byte', 'b', '=b', '<b', '>b'], typing.Literal['short', 'h', '=h', '<h', '>h'], typing.Literal['intc', 'i', '=i', '<i', '>i'], typing.Literal['intp', 'int0', 'p', '=p', '<p', '>p'], typing.Literal['long', 'int', 'int_', 'l', '=l', '<l', '>l'], typing.Literal['longlong', 'q', '=q', '<q', '>q']]
_DTypeLikeNested: typing._SpecialForm  # value = typing.Any
_DTypeLikeObject: typing._UnionGenericAlias  # value = typing.Union[type, numpy.dtype[numpy.object_], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.object_]], typing.Literal['object', 'object_', 'O', '=O', '<O', '>O']]
_DTypeLikeStr: typing._UnionGenericAlias  # value = typing.Union[type[str], type[numpy.str_], numpy.dtype[numpy.str_], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.str_]], typing.Literal['str', 'str_', 'str0', 'unicode', 'unicode_', 'U', '=U', '<U', '>U']]
_DTypeLikeTD64: typing._UnionGenericAlias  # value = typing.Union[type[numpy.datetime64], numpy.dtype[numpy.datetime64], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.datetime64]], typing.Literal['datetime64', '=datetime64', '<datetime64', '>datetime64', 'datetime64[Y]', '=datetime64[Y]', '<datetime64[Y]', '>datetime64[Y]', 'datetime64[M]', '=datetime64[M]', '<datetime64[M]', '>datetime64[M]', 'datetime64[W]', '=datetime64[W]', '<datetime64[W]', '>datetime64[W]', 'datetime64[D]', '=datetime64[D]', '<datetime64[D]', '>datetime64[D]', 'datetime64[h]', '=datetime64[h]', '<datetime64[h]', '>datetime64[h]', 'datetime64[m]', '=datetime64[m]', '<datetime64[m]', '>datetime64[m]', 'datetime64[s]', '=datetime64[s]', '<datetime64[s]', '>datetime64[s]', 'datetime64[ms]', '=datetime64[ms]', '<datetime64[ms]', '>datetime64[ms]', 'datetime64[us]', '=datetime64[us]', '<datetime64[us]', '>datetime64[us]', 'datetime64[ns]', '=datetime64[ns]', '<datetime64[ns]', '>datetime64[ns]', 'datetime64[ps]', '=datetime64[ps]', '<datetime64[ps]', '>datetime64[ps]', 'datetime64[fs]', '=datetime64[fs]', '<datetime64[fs]', '>datetime64[fs]', 'datetime64[as]', '=datetime64[as]', '<datetime64[as]', '>datetime64[as]', 'M', '=M', '<M', '>M', 'M8', '=M8', '<M8', '>M8', 'M8[Y]', '=M8[Y]', '<M8[Y]', '>M8[Y]', 'M8[M]', '=M8[M]', '<M8[M]', '>M8[M]', 'M8[W]', '=M8[W]', '<M8[W]', '>M8[W]', 'M8[D]', '=M8[D]', '<M8[D]', '>M8[D]', 'M8[h]', '=M8[h]', '<M8[h]', '>M8[h]', 'M8[m]', '=M8[m]', '<M8[m]', '>M8[m]', 'M8[s]', '=M8[s]', '<M8[s]', '>M8[s]', 'M8[ms]', '=M8[ms]', '<M8[ms]', '>M8[ms]', 'M8[us]', '=M8[us]', '<M8[us]', '>M8[us]', 'M8[ns]', '=M8[ns]', '<M8[ns]', '>M8[ns]', 'M8[ps]', '=M8[ps]', '<M8[ps]', '>M8[ps]', 'M8[fs]', '=M8[fs]', '<M8[fs]', '>M8[fs]', 'M8[as]', '=M8[as]', '<M8[as]', '>M8[as]']]
_DTypeLikeUInt: typing._UnionGenericAlias  # value = typing.Union[type[numpy.unsignedinteger], numpy.dtype[numpy.unsignedinteger], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.unsignedinteger]], typing.Literal['uint8', 'u1', '=u1', '<u1', '>u1'], typing.Literal['uint16', 'u2', '=u2', '<u2', '>u2'], typing.Literal['uint32', 'u4', '=u4', '<u4', '>u4'], typing.Literal['uint64', 'u8', '=u8', '<u8', '>u8'], typing.Literal['ubyte', 'B', '=B', '<B', '>B'], typing.Literal['ushort', 'H', '=H', '<H', '>H'], typing.Literal['uintc', 'I', '=I', '<I', '>I'], typing.Literal['uintp', 'uint0', 'P', '=P', '<P', '>P'], typing.Literal['ulong', 'uint', 'L', '=L', '<L', '>L'], typing.Literal['ulonglong', 'Q', '=Q', '<Q', '>Q']]
_DTypeLikeVoid: typing._UnionGenericAlias  # value = typing.Union[type[numpy.void], numpy.dtype[numpy.void], numpy._typing._dtype_like._SupportsDType[numpy.dtype[numpy.void]], typing.Literal['void', 'void0', 'V', '=V', '<V', '>V'], tuple[typing.Any, int], tuple[typing.Any, typing.Union[typing.SupportsIndex, collections.abc.Sequence[typing.SupportsIndex]]], list[typing.Any], numpy._typing._dtype_like._DTypeDict, tuple[typing.Any, typing.Any]]
_DType_co: typing.TypeVar  # value = +_DType_co
_DoubleCodes: typing._LiteralGenericAlias  # value = typing.Literal['double', 'float', 'float_', 'd', '=d', '<d', '>d']
_Float16Codes: typing._LiteralGenericAlias  # value = typing.Literal['float16', 'f2', '=f2', '<f2', '>f2']
_Float32Codes: typing._LiteralGenericAlias  # value = typing.Literal['float32', 'f4', '=f4', '<f4', '>f4']
_Float64Codes: typing._LiteralGenericAlias  # value = typing.Literal['float64', 'f8', '=f8', '<f8', '>f8']
_HalfCodes: typing._LiteralGenericAlias  # value = typing.Literal['half', 'e', '=e', '<e', '>e']
_Int16Codes: typing._LiteralGenericAlias  # value = typing.Literal['int16', 'i2', '=i2', '<i2', '>i2']
_Int32Codes: typing._LiteralGenericAlias  # value = typing.Literal['int32', 'i4', '=i4', '<i4', '>i4']
_Int64Codes: typing._LiteralGenericAlias  # value = typing.Literal['int64', 'i8', '=i8', '<i8', '>i8']
_Int8Codes: typing._LiteralGenericAlias  # value = typing.Literal['int8', 'i1', '=i1', '<i1', '>i1']
_IntCCodes: typing._LiteralGenericAlias  # value = typing.Literal['intc', 'i', '=i', '<i', '>i']
_IntCodes: typing._LiteralGenericAlias  # value = typing.Literal['long', 'int', 'int_', 'l', '=l', '<l', '>l']
_IntPCodes: typing._LiteralGenericAlias  # value = typing.Literal['intp', 'int0', 'p', '=p', '<p', '>p']
_LongDoubleCodes: typing._LiteralGenericAlias  # value = typing.Literal['longdouble', 'longfloat', 'g', '=g', '<g', '>g']
_LongLongCodes: typing._LiteralGenericAlias  # value = typing.Literal['longlong', 'q', '=q', '<q', '>q']
_ObjectCodes: typing._LiteralGenericAlias  # value = typing.Literal['object', 'object_', 'O', '=O', '<O', '>O']
_SCT: typing.TypeVar  # value = ~_SCT
_ShapeLike: typing._UnionGenericAlias  # value = typing.Union[typing.SupportsIndex, collections.abc.Sequence[typing.SupportsIndex]]
_ShortCodes: typing._LiteralGenericAlias  # value = typing.Literal['short', 'h', '=h', '<h', '>h']
_SingleCodes: typing._LiteralGenericAlias  # value = typing.Literal['single', 'f', '=f', '<f', '>f']
_StrCodes: typing._LiteralGenericAlias  # value = typing.Literal['str', 'str_', 'str0', 'unicode', 'unicode_', 'U', '=U', '<U', '>U']
_TD64Codes: typing._LiteralGenericAlias  # value = typing.Literal['timedelta64', '=timedelta64', '<timedelta64', '>timedelta64', 'timedelta64[Y]', '=timedelta64[Y]', '<timedelta64[Y]', '>timedelta64[Y]', 'timedelta64[M]', '=timedelta64[M]', '<timedelta64[M]', '>timedelta64[M]', 'timedelta64[W]', '=timedelta64[W]', '<timedelta64[W]', '>timedelta64[W]', 'timedelta64[D]', '=timedelta64[D]', '<timedelta64[D]', '>timedelta64[D]', 'timedelta64[h]', '=timedelta64[h]', '<timedelta64[h]', '>timedelta64[h]', 'timedelta64[m]', '=timedelta64[m]', '<timedelta64[m]', '>timedelta64[m]', 'timedelta64[s]', '=timedelta64[s]', '<timedelta64[s]', '>timedelta64[s]', 'timedelta64[ms]', '=timedelta64[ms]', '<timedelta64[ms]', '>timedelta64[ms]', 'timedelta64[us]', '=timedelta64[us]', '<timedelta64[us]', '>timedelta64[us]', 'timedelta64[ns]', '=timedelta64[ns]', '<timedelta64[ns]', '>timedelta64[ns]', 'timedelta64[ps]', '=timedelta64[ps]', '<timedelta64[ps]', '>timedelta64[ps]', 'timedelta64[fs]', '=timedelta64[fs]', '<timedelta64[fs]', '>timedelta64[fs]', 'timedelta64[as]', '=timedelta64[as]', '<timedelta64[as]', '>timedelta64[as]', 'm', '=m', '<m', '>m', 'm8', '=m8', '<m8', '>m8', 'm8[Y]', '=m8[Y]', '<m8[Y]', '>m8[Y]', 'm8[M]', '=m8[M]', '<m8[M]', '>m8[M]', 'm8[W]', '=m8[W]', '<m8[W]', '>m8[W]', 'm8[D]', '=m8[D]', '<m8[D]', '>m8[D]', 'm8[h]', '=m8[h]', '<m8[h]', '>m8[h]', 'm8[m]', '=m8[m]', '<m8[m]', '>m8[m]', 'm8[s]', '=m8[s]', '<m8[s]', '>m8[s]', 'm8[ms]', '=m8[ms]', '<m8[ms]', '>m8[ms]', 'm8[us]', '=m8[us]', '<m8[us]', '>m8[us]', 'm8[ns]', '=m8[ns]', '<m8[ns]', '>m8[ns]', 'm8[ps]', '=m8[ps]', '<m8[ps]', '>m8[ps]', 'm8[fs]', '=m8[fs]', '<m8[fs]', '>m8[fs]', 'm8[as]', '=m8[as]', '<m8[as]', '>m8[as]']
_UByteCodes: typing._LiteralGenericAlias  # value = typing.Literal['ubyte', 'B', '=B', '<B', '>B']
_UInt16Codes: typing._LiteralGenericAlias  # value = typing.Literal['uint16', 'u2', '=u2', '<u2', '>u2']
_UInt32Codes: typing._LiteralGenericAlias  # value = typing.Literal['uint32', 'u4', '=u4', '<u4', '>u4']
_UInt64Codes: typing._LiteralGenericAlias  # value = typing.Literal['uint64', 'u8', '=u8', '<u8', '>u8']
_UInt8Codes: typing._LiteralGenericAlias  # value = typing.Literal['uint8', 'u1', '=u1', '<u1', '>u1']
_UIntCCodes: typing._LiteralGenericAlias  # value = typing.Literal['uintc', 'I', '=I', '<I', '>I']
_UIntCodes: typing._LiteralGenericAlias  # value = typing.Literal['ulong', 'uint', 'L', '=L', '<L', '>L']
_UIntPCodes: typing._LiteralGenericAlias  # value = typing.Literal['uintp', 'uint0', 'P', '=P', '<P', '>P']
_ULongLongCodes: typing._LiteralGenericAlias  # value = typing.Literal['ulonglong', 'Q', '=Q', '<Q', '>Q']
_UShortCodes: typing._LiteralGenericAlias  # value = typing.Literal['ushort', 'H', '=H', '<H', '>H']
_VoidCodes: typing._LiteralGenericAlias  # value = typing.Literal['void', 'void0', 'V', '=V', '<V', '>V']
_VoidDTypeLike: typing._UnionGenericAlias  # value = typing.Union[tuple[typing.Any, int], tuple[typing.Any, typing.Union[typing.SupportsIndex, collections.abc.Sequence[typing.SupportsIndex]]], list[typing.Any], numpy._typing._dtype_like._DTypeDict, tuple[typing.Any, typing.Any]]
